GET http://localhost:5001/fuel-sales HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5kb2UiLCJyb2xlIjoiQURNSU4iLCJpZCI6ImZjMTUxZjI2LWE2NjUtNGQxMS05MmIwLTFmZjEwYTVhNzdjYyIsImlhdCI6MTc0MDg2ODk2OCwiZXhwIjoxNzQwOTU1MzY4fQ.IP-2ac2EvWEDU7O_j48OogBTgadVYDWcidCZiVaKPRM