
POST http://localhost:5001/product-sales HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5kb2UiLCJyb2xlIjoiQURNSU4iLCJpZCI6ImQwMTk3MDZkLTAwYzYtNGNhMC1hMzIwLTNmNWUxZWJiZTFiNyIsImlhdCI6MTc0MjUwODQyNSwiZXhwIjoxNzQyNTk0ODI1fQ.XFOO6QHJMjbgAYRDwOIUVI_bgfES9EYIOgQ9fe6-d_o

{
    "user_id": "d019706d-00c6-4ca0-a320-3f5e1ebbe1b7",
    "sale_details": [
      {
        "product_id": "01fe187e-b237-4f27-8add-16b10fc8e20f",
        "quantity": 2,
        "unit_price": 45.50
      },
      {
        "product_id": "0ef694a9-71b8-42a0-af5c-0a195fbc27ba",
        "quantity": 3,
        "unit_price": 19.25
      }
    ]
  }